import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import '@/styles/globals.css'

import { ClerkProvider } from '@clerk/nextjs'

import ExitModal from '@/components/Modals/ExitModal'
import HeartsModal from '@/components/Modals/HeartsModal'
import { PracticeModal } from '@/components/Modals/PracticeModal'
import { Toaster } from '@/components/ui/Sonner'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang='en'>
        <body className={font.className}>
          <Toaster richColors />

          <ExitModal />

          <HeartsModal />

          <PracticeModal />

          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
